using System.Globalization;

namespace GGHub.Infrastructure.Localization;

public static class AppText
{
    private static readonly IReadOnlyDictionary<string, string> Tr = new Dictionary<string, string>
    {
        ["common.invalidAction"] = "Geçersiz işlem.",
        ["common.userNotFound"] = "Kullanıcı bulunamadı.",
        ["auth.registerSuccess"] = "Kayıt başarılı. Lütfen e-posta adresinizi doğrulayın.",
        ["auth.registerError"] = "Kayıt sırasında bir hata oluştu.",
        ["auth.loginInvalid"] = "E-posta veya şifre hatalı.",
        ["auth.loginError"] = "Giriş sırasında bir hata oluştu.",
        ["auth.invalidRefreshToken"] = "Geçersiz refresh token.",
        ["auth.forgotPasswordSuccess"] = "Eğer bu e-posta kayıtlıysa, şifre sıfırlama kodu gönderildi.",
        ["auth.genericRetry"] = "Bir hata oluştu. Lütfen tekrar deneyin.",
        ["auth.resetPasswordInvalid"] = "Geçersiz veya süresi dolmuş kod.",
        ["auth.passwordUpdated"] = "Şifreniz başarıyla güncellendi.",
        ["auth.invalidUserInfo"] = "Geçersiz kullanıcı bilgisi.",
        ["auth.currentPasswordInvalid"] = "Mevcut şifre hatalı.",
        ["auth.passwordUpdatedSessionsRevoked"] = "Şifreniz başarıyla güncellendi. Tüm oturumlarınız sonlandırıldı.",
        ["auth.changePasswordError"] = "Şifre değiştirme sırasında bir hata oluştu.",
        ["auth.verifyEmailRequired"] = "Giriş yapmadan önce e-posta adresinizi doğrulamanız gerekmektedir.",
        ["auth.accountSuspended"] = "Hesabınız askıya alınmıştır. Lütfen yönetici ile iletişime geçin.",
        ["auth.emailAccountSuspended"] = "Bu e-posta adresi ile ilişkili hesap askıya alınmıştır.",
        ["auth.emailAlreadyInUse"] = "Bu e-posta adresi zaten kullanılıyor.",
        ["auth.usernameAccountSuspended"] = "Bu kullanıcı adı ile ilişkili hesap askıya alınmıştır.",
        ["auth.usernameAlreadyInUse"] = "Bu kullanıcı adı zaten kullanılıyor.",
        ["auth.samePassword"] = "Yeni şifre mevcut şifre ile aynı olamaz.",
        ["auth.emailVerificationSubject"] = "GGHub Hesap Doğrulama",
        ["auth.passwordResetSubject"] = "GGHub - Şifre Sıfırlama Kodu",
        ["auth.passwordChangedSubject"] = "GGHub - Şifre Değişikliği Bildirimi",
        ["lists.notFoundOrUnauthorized"] = "Liste bulunamadı veya bu listeyi görme yetkiniz yok.",
        ["lists.notFound"] = "Liste bulunamadı.",
        ["lists.updateFailed"] = "Liste güncellenemedi.",
        ["lists.deleteFailed"] = "Liste silinemedi.",
        ["lists.nameAlreadyExists"] = "Bu isimde bir listeniz zaten mevcut.",
        ["lists.permissionDenied"] = "Bu liste üzerinde işlem yapma yetkiniz yok.",
        ["lists.gameAlreadyExists"] = "Bu oyun bu listede zaten mevcut.",
        ["lists.favoritesLimit"] = "Favori listesine en fazla 5 oyun ekleyebilirsiniz.",
        ["lists.loginRequiredToView"] = "Bu listeyi görüntülemek için giriş yapmalısınız.",
        ["lists.viewPermissionDenied"] = "Bu listeyi görme yetkiniz yok.",
        ["lists.followersOnlyView"] = "Bu listeyi sadece sahibinin takipçileri görebilir.",
        ["lists.deleteNotFound"] = "Silinecek liste bulunamadı.",
        ["lists.otherNameAlreadyExists"] = "Bu isimde başka bir listeniz zaten mevcut.",
        ["lists.wishlistAdded"] = "İstek listesine eklendi",
        ["lists.wishlistRemoved"] = "İstek listesinden çıkarıldı",
        ["lists.loginRequired"] = "Giriş yapılmalı.",
        ["lists.favoriteAdded"] = "Favorilere eklendi",
        ["lists.favoriteRemoved"] = "Favorilerden çıkarıldı",
        ["lists.defaultWishlistName"] = "İstek Listem",
        ["lists.defaultWishlistDescription"] = "Takip ettiğim oyunlar",
        ["lists.defaultFavoritesName"] = "Favori Oyunlarım",
        ["lists.defaultFavoritesDescription"] = "En sevdiğim, vitrinlik oyunlar.",
        ["lists.newGameAddedNotification"] = "Takip ettiğin '{name}' listesine yeni bir oyun eklendi.",
        ["admin.reportNotFound"] = "Rapor bulunamadı.",
        ["admin.reportResponseSaved"] = "Yanıt kaydedildi ve rapor kapatıldı.",
        ["admin.reportStatusUpdated"] = "Rapor durumu başarıyla güncellendi.",
        ["admin.userNotFound"] = "Kullanıcı bulunamadı.",
        ["admin.userNotFoundOrNotBanned"] = "Kullanıcı bulunamadı veya zaten banlı değil.",
        ["admin.userBanned"] = "Kullanıcı başarıyla askıya alındı.",
        ["admin.userUnbanned"] = "Kullanıcı yasağı başarıyla kaldırıldı.",
        ["admin.userRoleUpdated"] = "Kullanıcı rolü başarıyla güncellendi.",
        ["admin.cannotBanSelf"] = "Adminler kendilerini askıya alamaz.",
        ["admin.cannotChangeOwnRole"] = "Adminler kendi rollerini değiştiremez.",
        ["admin.invalidRole"] = "Geçersiz rol değeri. Rol 'Admin' veya 'User' olmalıdır.",
        ["admin.gameNotFound"] = "Oyun bulunamadı.",
        ["admin.syncTimeout"] = "'{name}' için işlem zaman aşımına uğradı (Metacritic yanıt vermedi).",
        ["admin.serverError"] = "Sunucu hatası oluştu.",
        ["admin.metacriticScoreNotFound"] = "'{name}' için Metacritic puanı bulunamadı",
        ["admin.metacriticScoreUpdated"] = "'{name}' için Metacritic puanı güncellendi",
        ["admin.syncLogMissing"] = "Henüz bir log dosyası oluşmadı.",
        ["admin.authorizedUserMissing"] = "Yetkili kullanıcı kimliği token'da bulunamadı.",
        ["admin.testMessage"] = "Tebrikler, bu mesajı sadece adminler görebilir!",
        ["messages.recipientNotFound"] = "Alıcı kullanıcı bulunamadı.",
        ["messages.cannotMessageBlockedUser"] = "Bu kullanıcıya mesaj gönderemezsiniz veya bu kullanıcıyı engellediğiniz için mesaj gönderemezsiniz.",
        ["messages.cannotMessageSelf"] = "Kendinize mesaj gönderemezsiniz.",
        ["messages.userNotAcceptingMessages"] = "Bu kullanıcı mesaj kabul etmiyor.",
        ["messages.followingOnly"] = "Bu kullanıcı sadece takip ettiği kişilerden mesaj kabul ediyor.",
        ["messages.threadUserNotFound"] = "Konuşulacak kullanıcı bulunamadı.",
        ["notifications.notificationNotFound"] = "Bildirim bulunamadı.",
        ["profiles.userNotFoundOrInvalidAction"] = "Kullanıcı bulunamadı veya geçersiz işlem.",
        ["profiles.invalidAction"] = "Geçersiz işlem.",
        ["report.currentUserMissing"] = "Kullanıcı kimliği bulunamadı.",
        ["report.reviewReported"] = "İnceleme başarıyla raporlandı.",
        ["report.userReported"] = "Kullanıcı başarıyla raporlandı.",
        ["report.listReported"] = "Liste başarıyla raporlandı.",
        ["report.commentReported"] = "Yorum başarıyla raporlandı.",
        ["report.cannotReportOwnContent"] = "Kendi içeriğinizi veya profilinizi raporlayamazsınız.",
        ["report.alreadyReported"] = "Bu içeriği zaten raporladınız.",
        ["report.reviewNotFound"] = "Raporlanacak yorum bulunamadı.",
        ["report.userNotFound"] = "Raporlanacak kullanıcı bulunamadı.",
        ["report.listNotFound"] = "Raporlanacak liste bulunamadı.",
        ["report.commentNotFound"] = "Raporlanacak liste yorumu bulunamadı.",
        ["search.minSearchLength"] = "Arama metni en az 3 karakter olmalıdır.",
        ["search.minQueryLength"] = "Arama sorgusu en az 3 karakter olmalıdır.",
        ["reviews.alreadyReviewed"] = "Bu oyuna zaten bir yorum yapmışsınız.",
        ["reviews.reviewNotFoundForVote"] = "Oylanacak yorum bulunamadı.",
        ["reviews.cannotVoteOwnReview"] = "Kendi yorumunuzu oylayamazsınız.",
        ["reviews.invalidVoteValue"] = "Oy değeri sadece +1 veya -1 olabilir.",
        ["reviews.reviewVoteNotificationPositive"] = "{username}, incelemene olumlu oy verdi.",
        ["reviews.reviewVoteNotificationNegative"] = "{username}, incelemene olumsuz oy verdi.",
        ["comments.updateFailed"] = "Yorum güncellenemedi.",
        ["comments.deleteFailed"] = "Yorum silinemedi.",
        ["comments.voteFailed"] = "Oylama işlemi başarısız.",
        ["comments.notFound"] = "Yorum bulunamadı.",
        ["comments.editPermissionDenied"] = "Bu yorumu düzenleme yetkiniz yok.",
        ["comments.deletePermissionDenied"] = "Bu yorumu silme yetkiniz yok.",
        ["comments.parentNotFound"] = "Cevap yazılmak istenen ana yorum bulunamadı.",
        ["comments.cannotVoteOwnComment"] = "Kendi yorumunuzu oylayamazsınız.",
        ["comments.invalidVoteValue"] = "Oy değeri 1 veya -1 olmalıdır.",
        ["comments.viewPermissionDenied"] = "Bu listeyi görme (ve yorum yapma) yetkiniz yok.",
        ["ratings.cannotRateOwnList"] = "Kendi listenizi puanlayamazsınız.",
        ["ratings.viewPermissionDenied"] = "Bu listeyi görme (ve puanlama) yetkiniz yok.",
        ["ratings.followersOnly"] = "Bu listeyi sadece sahibinin takipçileri puanlayabilir.",
        ["photo.userNotFound"] = "Kullanıcı bulunamadı.",
        ["photo.fileEmpty"] = "Dosya boş olamaz.",
        ["photo.invalidFormat"] = "Geçersiz dosya formatı. Gelen format: '{extension}'. Sadece JPG, PNG, GIF, WEBP desteklenir.",
        ["photo.fileTooLarge"] = "Dosya boyutu 5MB'dan büyük olamaz.",
        ["photo.bucketConfigMissing"] = "R2 bucket yapılandırması bulunamadı.",
        ["photo.publicUrlConfigMissing"] = "R2 public URL yapılandırması bulunamadı.",
        ["social.followNotification"] = "{username} seni takip etmeye başladı.",
        ["social.listFollowNotification"] = "{username}, '{listName}' adlı listen takip etmeye başladı.",
        ["config.geminiApiKeyMissing"] = "Gemini API Key bulunamadı.",
        ["rawg.gameNotFoundById"] = "RAWG API'sinde {rawgId} ID'li oyun bulunamadı.",
        ["metacritic.noResponse30Seconds"] = "30 saniye içinde yanıt alınamadı.",
    };

    private static readonly IReadOnlyDictionary<string, string> EnUs = new Dictionary<string, string>
    {
        ["common.invalidAction"] = "Invalid action.",
        ["common.userNotFound"] = "User not found.",
        ["auth.registerSuccess"] = "Registration successful. Please verify your email address.",
        ["auth.registerError"] = "An error occurred during registration.",
        ["auth.loginInvalid"] = "Incorrect email or password.",
        ["auth.loginError"] = "An error occurred during login.",
        ["auth.invalidRefreshToken"] = "Invalid refresh token.",
        ["auth.forgotPasswordSuccess"] = "If this email is registered, a password reset code has been sent.",
        ["auth.genericRetry"] = "Something went wrong. Please try again.",
        ["auth.resetPasswordInvalid"] = "The code is invalid or has expired.",
        ["auth.passwordUpdated"] = "Your password has been updated successfully.",
        ["auth.invalidUserInfo"] = "Invalid user information.",
        ["auth.currentPasswordInvalid"] = "The current password is incorrect.",
        ["auth.passwordUpdatedSessionsRevoked"] = "Your password has been updated successfully. All of your sessions have been signed out.",
        ["auth.changePasswordError"] = "An error occurred while changing the password.",
        ["auth.verifyEmailRequired"] = "You must verify your email address before signing in.",
        ["auth.accountSuspended"] = "Your account has been suspended. Please contact an administrator.",
        ["auth.emailAccountSuspended"] = "The account associated with this email address has been suspended.",
        ["auth.emailAlreadyInUse"] = "This email address is already in use.",
        ["auth.usernameAccountSuspended"] = "The account associated with this username has been suspended.",
        ["auth.usernameAlreadyInUse"] = "This username is already in use.",
        ["auth.samePassword"] = "The new password cannot be the same as the current password.",
        ["auth.emailVerificationSubject"] = "GGHub Account Verification",
        ["auth.passwordResetSubject"] = "GGHub - Password Reset Code",
        ["auth.passwordChangedSubject"] = "GGHub - Password Change Notification",
        ["lists.notFoundOrUnauthorized"] = "The list was not found or you do not have permission to view it.",
        ["lists.notFound"] = "List not found.",
        ["lists.updateFailed"] = "The list could not be updated.",
        ["lists.deleteFailed"] = "The list could not be deleted.",
        ["lists.nameAlreadyExists"] = "You already have a list with this name.",
        ["lists.permissionDenied"] = "You do not have permission to perform this action on this list.",
        ["lists.gameAlreadyExists"] = "This game is already in the list.",
        ["lists.favoritesLimit"] = "You can add at most 5 games to the favorites list.",
        ["lists.loginRequiredToView"] = "You must sign in to view this list.",
        ["lists.viewPermissionDenied"] = "You do not have permission to view this list.",
        ["lists.followersOnlyView"] = "Only the owner's followers can view this list.",
        ["lists.deleteNotFound"] = "The list to delete was not found.",
        ["lists.otherNameAlreadyExists"] = "You already have another list with this name.",
        ["lists.wishlistAdded"] = "Added to wishlist",
        ["lists.wishlistRemoved"] = "Removed from wishlist",
        ["lists.loginRequired"] = "You must be signed in.",
        ["lists.favoriteAdded"] = "Added to favorites",
        ["lists.favoriteRemoved"] = "Removed from favorites",
        ["lists.defaultWishlistName"] = "My Wishlist",
        ["lists.defaultWishlistDescription"] = "Games I want to keep track of",
        ["lists.defaultFavoritesName"] = "My Favorite Games",
        ["lists.defaultFavoritesDescription"] = "My favorite showcase games.",
        ["lists.newGameAddedNotification"] = "A new game was added to the '{name}' list you follow.",
        ["admin.reportNotFound"] = "Report not found.",
        ["admin.reportResponseSaved"] = "Response saved and the report has been closed.",
        ["admin.reportStatusUpdated"] = "Report status updated successfully.",
        ["admin.userNotFound"] = "User not found.",
        ["admin.userNotFoundOrNotBanned"] = "User not found or is not banned.",
        ["admin.userBanned"] = "User suspended successfully.",
        ["admin.userUnbanned"] = "User suspension removed successfully.",
        ["admin.userRoleUpdated"] = "User role updated successfully.",
        ["admin.cannotBanSelf"] = "Admins cannot suspend themselves.",
        ["admin.cannotChangeOwnRole"] = "Admins cannot change their own roles.",
        ["admin.invalidRole"] = "Invalid role value. The role must be 'Admin' or 'User'.",
        ["admin.gameNotFound"] = "Game not found.",
        ["admin.syncTimeout"] = "The operation timed out for '{name}' (Metacritic did not respond).",
        ["admin.serverError"] = "A server error occurred.",
        ["admin.metacriticScoreNotFound"] = "Metacritic score could not be found for '{name}'",
        ["admin.metacriticScoreUpdated"] = "Metacritic score updated for '{name}'",
        ["admin.syncLogMissing"] = "No log file has been created yet.",
        ["admin.authorizedUserMissing"] = "Authorized user id could not be found in the token.",
        ["admin.testMessage"] = "Congratulations, only admins can see this message!",
        ["messages.recipientNotFound"] = "Recipient user not found.",
        ["messages.cannotMessageBlockedUser"] = "You cannot send a message to this user because one of you has blocked the other.",
        ["messages.cannotMessageSelf"] = "You cannot send a message to yourself.",
        ["messages.userNotAcceptingMessages"] = "This user is not accepting messages.",
        ["messages.followingOnly"] = "This user only accepts messages from people they follow.",
        ["messages.threadUserNotFound"] = "Conversation partner not found.",
        ["notifications.notificationNotFound"] = "Notification not found.",
        ["profiles.userNotFoundOrInvalidAction"] = "User not found or invalid action.",
        ["profiles.invalidAction"] = "Invalid action.",
        ["report.currentUserMissing"] = "User id could not be found.",
        ["report.reviewReported"] = "Review reported successfully.",
        ["report.userReported"] = "User reported successfully.",
        ["report.listReported"] = "List reported successfully.",
        ["report.commentReported"] = "Comment reported successfully.",
        ["report.cannotReportOwnContent"] = "You cannot report your own content or profile.",
        ["report.alreadyReported"] = "You have already reported this content.",
        ["report.reviewNotFound"] = "The review to report was not found.",
        ["report.userNotFound"] = "The user to report was not found.",
        ["report.listNotFound"] = "The list to report was not found.",
        ["report.commentNotFound"] = "The list comment to report was not found.",
        ["search.minSearchLength"] = "Search text must be at least 3 characters.",
        ["search.minQueryLength"] = "Search query must be at least 3 characters.",
        ["reviews.alreadyReviewed"] = "You have already reviewed this game.",
        ["reviews.reviewNotFoundForVote"] = "The review to vote on was not found.",
        ["reviews.cannotVoteOwnReview"] = "You cannot vote on your own review.",
        ["reviews.invalidVoteValue"] = "Vote value can only be +1 or -1.",
        ["reviews.reviewVoteNotificationPositive"] = "{username} upvoted your review.",
        ["reviews.reviewVoteNotificationNegative"] = "{username} downvoted your review.",
        ["comments.updateFailed"] = "Comment could not be updated.",
        ["comments.deleteFailed"] = "Comment could not be deleted.",
        ["comments.voteFailed"] = "Voting failed.",
        ["comments.notFound"] = "Comment not found.",
        ["comments.editPermissionDenied"] = "You do not have permission to edit this comment.",
        ["comments.deletePermissionDenied"] = "You do not have permission to delete this comment.",
        ["comments.parentNotFound"] = "The parent comment you are trying to reply to was not found.",
        ["comments.cannotVoteOwnComment"] = "You cannot vote on your own comment.",
        ["comments.invalidVoteValue"] = "Vote value must be 1 or -1.",
        ["comments.viewPermissionDenied"] = "You do not have permission to view or comment on this list.",
        ["ratings.cannotRateOwnList"] = "You cannot rate your own list.",
        ["ratings.viewPermissionDenied"] = "You do not have permission to view or rate this list.",
        ["ratings.followersOnly"] = "Only the owner's followers can rate this list.",
        ["photo.userNotFound"] = "User not found.",
        ["photo.fileEmpty"] = "File cannot be empty.",
        ["photo.invalidFormat"] = "Invalid file format. Received '{extension}'. Only JPG, PNG, GIF, and WEBP are supported.",
        ["photo.fileTooLarge"] = "File size cannot exceed 5MB.",
        ["photo.bucketConfigMissing"] = "R2 bucket configuration is missing.",
        ["photo.publicUrlConfigMissing"] = "R2 public URL configuration is missing.",
        ["social.followNotification"] = "{username} started following you.",
        ["social.listFollowNotification"] = "{username} started following your list '{listName}'.",
        ["config.geminiApiKeyMissing"] = "Gemini API Key was not found.",
        ["rawg.gameNotFoundById"] = "Game with RAWG ID {rawgId} was not found.",
        ["metacritic.noResponse30Seconds"] = "No response was received within 30 seconds.",
    };

    public static string Get(string key, IDictionary<string, object?>? values = null)
    {
        var locale = ResolveLocale();
        var template = locale == "tr"
            ? Tr.GetValueOrDefault(key)
            : EnUs.GetValueOrDefault(key) ?? Tr.GetValueOrDefault(key);

        template ??= key;

        if (values is null || values.Count == 0)
        {
            return template;
        }

        foreach (var pair in values)
        {
            template = template.Replace($"{{{pair.Key}}}", Convert.ToString(pair.Value, CultureInfo.InvariantCulture));
        }

        return template;
    }

    private static string ResolveLocale()
    {
        var current = CultureInfo.CurrentUICulture.Name;
        if (string.Equals(current, "tr", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(current, "tr-TR", StringComparison.OrdinalIgnoreCase))
        {
            return "tr";
        }

        return "en-US";
    }
}
